In [5]:
weight = 0.1

def neural_network(input, weight):
    prediction = input * weight
    return prediction


In [6]:
number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[0]
pred = neural_network(input, weight)
print(pred)

0.8500000000000001


In [11]:
def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    
    for i in range(len(a)):
        output += (a[i] * b[i])
        
    return output


weights = [0.1, 0.2, 0]

def neural_network(input, weights):
    pred = w_sum(input, weights)
    return pred


toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

pred = neural_network(input, weights)
print(pred)

0.9800000000000001


In [12]:
def elementwise_multiplication(vec_a, vec_b):
    assert(len(vec_a) == len(vec_b))
    output = 0
    
    for i in range(len(vec_a)):
        output += vec_a[i] * vec_b[i]
        
    return output

def elementwise_addition(vec_a, vec_b):
    assert(len(vec_a) == len(vec_b))
    output = 0
    
    for i in range(len(vec_a)):
        output += vec_a[i] + vec_b[i]
        
    return output

def vector_sum(vec_a):
    output = 0
    for i in range(len(vec_a)):
        output += vec_a[i]
        
    return output

def vector_average(vec_a):
    return vector_sum(vec_a) / len(vec_a)
    
    

Код с использованием NumPy

In [13]:
import numpy as np
weights = np.array([0.1, 0.2, 0])
def neural_network(input, weights):
    pred = input.dot(weights)
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0],nfans[0]])
pred = neural_network(input, weights)
print(pred)

0.9800000000000001


In [6]:
import numpy as np

# игр % побед болельщиков

ih_wgt = пр.array([
            [0.1, 0.2, -0.1], # hid[0]
            [-0.1,0.1, 0.9], # hid[l]
            [0.1, 0.4, 0.1] ]).T # hid[2]

# hid[0] hid[l] hid[2]
hp_wgt = np.array([
            [0.3, 1.1, -0.3], # травмы?
            [0.1, 0.2, 0.0], # победа?
            [0.0, 1.3, 0.1] ]).T # печаль?

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred


toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65,0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0],wlrec[0],nfans[0]])

pred = neural_network(input,weights)
print(pred)

[0.2135 0.145  0.5065]


In [8]:
a = np.array([0,1,2,3])
b = np.array([4,5,6,7])
c = np.array([[0,1,2,3],
              [4,5,6,7]])
d = np.zeros((2,4))
e = np.random.rand(2,5)

print(a)
print(b)
print(c)
print(d)
print(e)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.1554207  0.63939147 0.36031766 0.96250677 0.07664194]
 [0.02727231 0.69064059 0.04962783 0.35060699 0.68223222]]


In [9]:
print(a * 0.1)
print(c * 0.2)
print(a * b)
print(a * b * 0.2)
print(a * c)

print(a * e)

[0.  0.1 0.2 0.3]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]


ValueError: operands could not be broadcast together with shapes (4,) (2,5) 

In [13]:
knob_weight = 0.5
input = 0.5
goal_pred = 0.8

pred = input * knob_weight

error = (pred - goal_pred) ** 2

print(error)

0.30250000000000005


In [19]:
#1
weight = 0.1

lr = 0.01

def neural_network(input, weight):
    
    prediction = input * weight
    return prediction

#2
number_of_toes = [8.5]
win_or_lose_binary = [1]

input = number_of_toes[0]
true = win_or_lose_binary[0]

pred = neural_network(input, weight)

error = (pred - true) ** 2
print(error)

#3

lr = 0.1

p_up = neural_network(input, weight) + lr

e_up = (p_up - true) ** 2
print(e_up)

#4

lr = 0.1

p_dn = neural_network(input, weight) - lr

e_dn = (p_dn - true) ** 2
print(e_dn)

#5

if (error > e_dn or
    error > e_up):
    if e_dn < e_up:
        weight -= lr
    if e_up < e_dn:
        weight += lr

0.022499999999999975
0.0024999999999999935
0.062499999999999944


In [24]:
weight = 0.5
input = 0.5
goal_prediction = 0.8

step_amount = 10

for iteration in range(1101):
    prediction = input * weight
    error = (prediction - goal_prediction) ** 2
    
    print("Error:" + str(error) + " Prediction:" + str(prediction))

    up_prediction = input * (weight + step_amount)
    up_error = (goal_prediction - up_prediction) ** 2

    down_prediction = input * (weight - step_amount)
    down_error = (goal_prediction - down_prediction) ** 2

    if(down_error < up_error):
        weight = weight - step_amount

    if(down_error > up_error):
        weight = weight + step_amount

Error:0.30250000000000005 Prediction:0.25
Error:19.802500000000002 Prediction:5.25
Error:0.30250000000000005 Prediction:0.25
Error:19.802500000000002 Prediction:5.25
Error:0.30250000000000005 Prediction:0.25
Error:19.802500000000002 Prediction:5.25
Error:0.30250000000000005 Prediction:0.25
Error:19.802500000000002 Prediction:5.25
Error:0.30250000000000005 Prediction:0.25
Error:19.802500000000002 Prediction:5.25
Error:0.30250000000000005 Prediction:0.25
Error:19.802500000000002 Prediction:5.25
Error:0.30250000000000005 Prediction:0.25
Error:19.802500000000002 Prediction:5.25
Error:0.30250000000000005 Prediction:0.25
Error:19.802500000000002 Prediction:5.25
Error:0.30250000000000005 Prediction:0.25
Error:19.802500000000002 Prediction:5.25
Error:0.30250000000000005 Prediction:0.25
Error:19.802500000000002 Prediction:5.25
Error:0.30250000000000005 Prediction:0.25
Error:19.802500000000002 Prediction:5.25
Error:0.30250000000000005 Prediction:0.25
Error:19.802500000000002 Prediction:5.25
Erro

In [25]:
weight = 0.5
goal_pred = 0.8
input = 0.5

for iteration in range(20):
    pred = input * weight
    error = (pred - goal_pred) ** 2
    direction_and_amount = (pred - goal_pred) * input
    weight = weight - direction_and_amount
    
    print("Error:" + str(error) + " Prediction:" + str(pred))

Error:0.30250000000000005 Prediction:0.25
Error:0.17015625000000004 Prediction:0.3875
Error:0.095712890625 Prediction:0.49062500000000003
Error:0.05383850097656251 Prediction:0.56796875
Error:0.03028415679931642 Prediction:0.6259765625
Error:0.0170348381996155 Prediction:0.669482421875
Error:0.00958209648728372 Prediction:0.70211181640625
Error:0.005389929274097089 Prediction:0.7265838623046875
Error:0.0030318352166796153 Prediction:0.7449378967285156
Error:0.0017054073093822882 Prediction:0.7587034225463867
Error:0.0009592916115275371 Prediction:0.76902756690979
Error:0.0005396015314842384 Prediction:0.7767706751823426
Error:0.000303525861459885 Prediction:0.7825780063867569
Error:0.00017073329707118678 Prediction:0.7869335047900676
Error:9.603747960254256e-05 Prediction:0.7902001285925507
Error:5.402108227642978e-05 Prediction:0.7926500964444131
Error:3.038685878049206e-05 Prediction:0.7944875723333098
Error:1.7092608064027242e-05 Prediction:0.7958656792499823
Error:9.614592036015323

In [26]:
weight, goal_pred, input = (0.0, 0.8, 0.5)

for iteration in range(4):
    
    pred = input * weight
    error = (pred - goal_pred) ** 2
    delta = pred - goal_pred
    weight_delta = delta * input
    weight = weight - weight_delta
    print("Error:" + str(error) + " Prediction:" + str(pred))

Error:0.6400000000000001 Prediction:0.0
Error:0.3600000000000001 Prediction:0.2
Error:0.2025 Prediction:0.35000000000000003
Error:0.11390625000000001 Prediction:0.4625


In [27]:
weight, goal_pred, input = (0.0, 0.8, 1.1)

for iteration in range(4):
    
    print("-----\nWeight:" + str(weight))
    pred = input * weight
    error = (pred - goal_pred) ** 2
    delta = pred - goal_pred
    weight_delta = delta * input
    weight = weight - weight_delta
    print("Error:" + str(error) + " Prediction:" + str(pred))
    print('Delta:' + str(delta) + ' Weight Delta:' + str(weight_delta))

-----
Weight:0.0
Error:0.6400000000000001 Prediction:0.0
Delta:-0.8 Weight Delta:-0.8800000000000001
-----
Weight:0.8800000000000001
Error:0.02822400000000005 Prediction:0.9680000000000002
Delta:0.16800000000000015 Weight Delta:0.1848000000000002
-----
Weight:0.6951999999999999
Error:0.0012446784000000064 Prediction:0.76472
Delta:-0.03528000000000009 Weight Delta:-0.0388080000000001
-----
Weight:0.734008
Error:5.4890317439999896e-05 Prediction:0.8074088
Delta:0.007408799999999993 Weight Delta:0.008149679999999992


In [41]:
weight = 0.5
goal_pred = 0.8
input = 2
alpha = 0.1

for iteration in range(20):
    pred = input * weight
    error = (pred - goal_pred) ** 2
    derivative = input * (pred - goal_pred)
    weight = weight - (alpha * derivative)
    
    print("Error:" + str(error) + " Prediction:" + str(pred))

Error:0.03999999999999998 Prediction:1.0
Error:0.0144 Prediction:0.92
Error:0.005183999999999993 Prediction:0.872
Error:0.0018662400000000014 Prediction:0.8432000000000001
Error:0.0006718464000000028 Prediction:0.8259200000000001
Error:0.00024186470400000033 Prediction:0.815552
Error:8.70712934399997e-05 Prediction:0.8093312
Error:3.134566563839939e-05 Prediction:0.80559872
Error:1.1284439629823931e-05 Prediction:0.803359232
Error:4.062398266736526e-06 Prediction:0.8020155392
Error:1.4624633760252567e-06 Prediction:0.8012093235200001
Error:5.264868153690924e-07 Prediction:0.8007255941120001
Error:1.8953525353291194e-07 Prediction:0.8004353564672001
Error:6.82326912718715e-08 Prediction:0.8002612138803201
Error:2.456376885786678e-08 Prediction:0.8001567283281921
Error:8.842956788836216e-09 Prediction:0.8000940369969153
Error:3.1834644439835434e-09 Prediction:0.8000564221981492
Error:1.1460471998340758e-09 Prediction:0.8000338533188895
Error:4.125769919393652e-10 Prediction:0.80002031199

In [46]:
weight = 0.5
goal_pred = 0.8
input = 0.5
alpha = 1

for iteration in range(20):
    pred = weight * input
    error = (goal_pred - pred) ** 2
    derivative = input * (pred - goal_pred)
    weight = weight - (alpha * derivative)
    
    print("Error:", str(error), " Prediction:", str(pred))

Error: 0.30250000000000005  Prediction: 0.25
Error: 0.17015625000000004  Prediction: 0.3875
Error: 0.095712890625  Prediction: 0.49062500000000003
Error: 0.05383850097656251  Prediction: 0.56796875
Error: 0.03028415679931642  Prediction: 0.6259765625
Error: 0.0170348381996155  Prediction: 0.669482421875
Error: 0.00958209648728372  Prediction: 0.70211181640625
Error: 0.005389929274097089  Prediction: 0.7265838623046875
Error: 0.0030318352166796153  Prediction: 0.7449378967285156
Error: 0.0017054073093822882  Prediction: 0.7587034225463867
Error: 0.0009592916115275371  Prediction: 0.76902756690979
Error: 0.0005396015314842384  Prediction: 0.7767706751823426
Error: 0.000303525861459885  Prediction: 0.7825780063867569
Error: 0.00017073329707118678  Prediction: 0.7869335047900676
Error: 9.603747960254256e-05  Prediction: 0.7902001285925507
Error: 5.402108227642978e-05  Prediction: 0.7926500964444131
Error: 3.038685878049206e-05  Prediction: 0.7944875723333098
Error: 1.7092608064027242e-05  